### ISSUE TITLE
What idiom to use with the modern syntax without cascading

### ISSUE THREAD

**Issue by mtopolnik** [cgrand/moustache#11]
Previously I had

``` clojure
(app
  ["a"] a-handler
  ["b"] b-handler
  [&]
  [wrap-x
   ["c" c-handler]
   ["d" d-handler]])
```

Without cascading this fails. What should I use instead to add middleware to a subset of the routes? Using a regexp that matches _c_ and _d_ would consume that segment so I wouldn't be able to dispatch on it.

Use higher-order middleware?

**Comment by cgrand** [comment]
I assume you meant:

```
(app
  ["a"] a-handler
  ["b"] b-handler
  [&]
  [wrap-x
    ["c"] c-handler
    ["d"] d-handler])
```

However I fail to see where cascading comes into play. I just tested it and its modernized version with no trouble.
To make things clear what I mean by cascading is maybe more aptly named "route shadowing": when two handlers were responding to a same routes you can't rely on order to implicit fix that, you'll have to be explicit. Explicitness can be just resorting to the old syntax which would warn that ordering matters here or a new option or fn making the ordering/exclusion obvious.

**Comment by mtopolnik** [comment]
Yes, I meant the brackets to be where you put them. In my code I get 404 unless I remove the `[&]` part. This minimal example seems not enough to reproduce this, I'll work some more to isolate the true problem. 

The order does matter in the old syntax, though, since

``` clojure
(app
  [&]
  [wrap-x
   ["c"] c-handler
   ["d"] d-handler]
  ["a"] a-handler
  ["b"] b-handler
)
```

would result in a 404 for /a and /b. These match the first route `&`, but its handler then fails to match:

``` clojure
user> ((app [&] [["a"] "a here"] ["c"] "c here") {:uri "/c"})
{:status 404}
user> ((app ["c"] "c here" [&] [["a"] "a here"]) {:uri "/c"})
{:status 200, :headers {"Content-Type" "text/plain;charset=UTF-8"}, :body "c here"}
```

**Comment by cgrand** [comment]
Ok I see. Legacy routes needed explicit passing and were implictly 404ing. This is a bad default for composistion. I just reversed that for modern syntax.

``` clojure
user> ((app [&] [["a"] "a here" [&] pass] ["c"] "c here") {:uri "/c"})
{:status 200, :headers {"Content-Type" "text/plain;charset=UTF-8"}, :body "c here"}
```

So in mondern syntax the [&] pass is not needed

**Comment by mtopolnik** [comment]
I reproduced it now, no idea what to make of it:

``` clojure
user> ((app :middlewares [] ["a"] "a here" [&] {["b"] "b here"}) {:uri "/a"})
{:status 200, :headers {"Content-Type" "text/plain;charset=UTF-8"}, :body "a here"}
user> ((app :middlewares [] ["ca"] "ca here" [&] {["b"] "b here"}) {:uri "/ca"})
{:status 404}
```

**Comment by cgrand** [comment]
With moustache as of today (with the change I mentioned), it works:

``` clojure
=> ((app :middlewares [] ["ca"] "ca here" [&] {["b"] "b here"}) {:uri "/ca"})
{:status 200, :headers {"Content-Type" "text/plain;charset=UTF-8"}, :body "ca here"}
```

Without the patch you would have to write

``` clojure
=> ((app :middlewares [] ["ca"] "ca here" [&] {["b"] "b here" [&] pass}) {:uri "/ca"})
{:status 200, :headers {"Content-Type" "text/plain;charset=UTF-8"}, :body "ca here"}
```

Can your reproduce my results?

**Comment by mtopolnik** [comment]
I see; didn't realize you just made the change. I was testing with alpha1. I've checked out the source and rerun it. It works, but now instead of `{:status 404}` I get just `nil`:

``` clojure
=> ((app :middlewares [] ["ca"] "ca here" [&] {["b"] "b here" [&] pass}) {:uri "/cab"})
nil
```

Am I supposed to wrap the top-level app in something that turns the `nil` into `404`?

**Comment by cgrand** [comment]
Thanks for alpha-testing. Right now there's no other option than wrapping.

A potentially better approach would be to treat a 404 returned by a route in a modern route-dispatch as meaning "try another route". This would deprecate #'pass (yeah!).

**Comment by mtopolnik** [comment]
This is an acceptable workaround against the current code:

``` clojure
=> ((app :middlewares [] [&] [{:status 404}] ["ca"] "ca here") {:uri "/cae"})
{:status 404}
```

**Comment by cgrand** [comment]
The implicit 404 is back in but properly handled in modern syntax. The workaround you proposed may have failed (returned a 404) if for "/ca" [&] was tested before ["ca"].

**Comment by mtopolnik** [comment]
Is the new behavior to test routes one-by-one like before, just in a non-specified order? That strikes me as a source of elusive bugs.

**Comment by cgrand** [comment]
This is the current implementation but it's a transitional implementation.

At some point I'd like moustache handlers to become queriable. Thus
moustache will be able to warn when two handlers may overlap (false
positive may arise because a handler may be opaque to moustache) and will
also be able to not test all routes one-by-one knowing the other ones are
hopeless.

With unordered routing by default, accidental shadowing will raise (one
day) a warning, if the user wants shadowing it will have to tell it
explicitly.
With ordering routing you can't tell whether shadowing occurs by accident
or by intent.

The elusive bugs you allude to may arise with the old syntax if you perform
some aggressive refactoring.

On Fri, Mar 1, 2013 at 2:51 PM, mtopolnik notifications@github.com wrote:

> Is the new behavior to test routes one-by-one like before, just in a
> non-specified order? That strikes me as a source of elusive bugs.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cgrand/moustache/issues/11#issuecomment-14290025
> .

## 

On Clojure http://clj-me.cgrand.net/
Clojure Programming http://clojurebook.com
Training, Consulting & Contracting http://lambdanext.eu/

**Comment by mtopolnik** [comment]
With your newest commit I get 404 most of the time:

``` clojure
=> ((app :middlewares [] ["a"] "a here" ["b"] "b here") {:uri "/a"})
{:status 404}
```

**Comment by cgrand** [comment]
Grmff 15' spent to realize I typed (or nil? ...) rather than (or (ni?  ...)
...)
Thanks for the report -- I added your code as a test case.

On Fri, Mar 1, 2013 at 3:17 PM, mtopolnik notifications@github.com wrote:

> With your newest commit I get 404 most of the time:
> 
> => ((app :middlewares [] ["a"] "a here" ["b"] "b here") {:uri "/a"}){:status 404}
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cgrand/moustache/issues/11#issuecomment-14291085
> .

## 

On Clojure http://clj-me.cgrand.net/
Clojure Programming http://clojurebook.com
Training, Consulting & Contracting http://lambdanext.eu/

**Comment by mtopolnik** [comment]
Heh heh, that's my failure mode with Clojure, too :)
