### ISSUE TITLE
Please support the HEAD method

### ISSUE THREAD

**Issue by thorwil** [cgrand/moustache#3]
Besides GET and POST. Apparently some sites use it to check user submitted links.

**Comment by cgrand** [comment]
There is no special support for GET and POST, you can add handlers for :PUT and :DELETE and :HEAD or even webdav verbs -- the list is open. If your handlers don't trigger for HEAD requests, it may be a problem upstream with ring or your ring adapter.

If I misunderstood your problem, please provide a small test case. Thanks.

**Comment by thorwil** [comment]
Ah, I was too quick to assume that since only get and post and any are mentioned, that would be it. And there are frameworks that manage to not support head.  It's really cool if that all works generically. Thanks!
