### ISSUE TITLE
Altering URIs breaks authentication in many apps

### ISSUE THREAD

**Issue by jwr** [cgrand/moustache#5]
We have a fairly large app that I've just started porting to moustache. So far things look very good, except for one thing: we use request authentication for some methods, similar to what Amazon AWS does. I have middleware that checks signatures computed from the URI and its params.

After introducing moustache, authentication started failing and I traced it down to moustache altering the :uri. I can understand the aesthetic value of writing freely-nestable apps that you can move from one part of the tree to another, but perhaps we could have an option to switch it off? After all, you move things around only in development, never afterwards, so it is not a production requirement. Also, altering (losing) data that came from the client seems hackish to me.

I'd much rather have an additional :routed-uri-part key in the request map than a destroyed original :uri.

Also, before you ask — we can't do authentication globally (before routing) because for performance reasons only some API methods are authenticated. Some do not need authentication and we can't afford doing it for all methods.

**Comment by cgrand** [comment]
You put the finger where it hurts: I'm not happy with this hack but as long as nobody was complaining it was low priority. I'm sorry to hear it breaks your code.

I'm going to revert :uri to its original value  but I'm not sure yet which value I'm going to add, maybe a ::context key. I have to think a little bit more about it.

**Comment by jwr** [comment]
I suspected you might want to do some thinking about the design, that's why I didn't try to include a pull request.

I can see the rationale for this hack, but it is a complete show-stopper for us, unfortunately. Perhaps you might revert :uri to its original value, do a quick release and then consider other options?

Alternatively, I guess we can just create a temporary fork, because we really like moustache otherwise.

**Comment by cgrand** [comment]
I pushed a 1.1 out, :uri is never touched, :path-info is the old :uri (as
per
http://groups.google.com/group/ring-clojure/browse_thread/thread/ae317453a6d10a/b6cf142660de7f42?pli=1)
and there's no :context key.

On Tue, Oct 4, 2011 at 12:18 PM, Jan Rychter <
reply@reply.github.com>wrote:

> I suspected you might want to do some thinking about the design, that's why
> I didn't try to include a pull request.
> 
> I can see the rationale for this hack, but it is a complete show-stopper
> for us, unfortunately. Perhaps you might revert :uri to its original value,
> do a quick release and then consider other options?
> 
> Alternatively, I guess we can just create a temporary fork, because we
> really like moustache otherwise.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/cgrand/moustache/issues/5#issuecomment-2284533

## 

Professional: http://cgrand.net/ (fr)
On Clojure: http://clj-me.cgrand.net/ (en)

**Comment by cgrand** [comment]
Closed as 1.1

**Comment by jwr** [comment]
Great, many thanks for the quick response!

**Comment by jwr** [comment]
[but please do not forget to deploy to clojars]

**Comment by cgrand** [comment]
huh? drat the scp failed! Uploaded for real this time.

On Thu, Oct 6, 2011 at 6:25 PM, Jan Rychter <
reply@reply.github.com>wrote:

> [but please do not forget to deploy to clojars]
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/cgrand/moustache/issues/5#issuecomment-2311854

## 

Professional: http://cgrand.net/ (fr)
On Clojure: http://clj-me.cgrand.net/ (en)

**Comment by jwr** [comment]
…and my request signatures verify just fine now. Thank you!
