### ISSUE TITLE
Overconstrained Dependency between Ring and Moustache

### ISSUE THREAD

**Issue by mschristiansen** [cgrand/moustache#7]
Doing a 'lein deps' returns a exception where Maven complains about overconstrained dependencies.

" ...
Caused by: org.apache.maven.artifact.versioning.OverConstrainedVersionException: No versions are present in the repository for the artifact with a range [0.2.0,)
  ring:ring-core:jar:null 
 ..."

This project.clj is enough to replicate the exception on my machine:
(defproject test "1.0.0-SNAPSHOT"
  :description "FIXME: write description"
  :dependencies [[org.clojure/clojure "1.3.0"]
                 [ring/ring-core "1.0.2"]
                 [net.cgrand/moustache "1.1.0"]])

I cloned Moustache, changed the version of the ring libraries to "1.0.2" pushed it to Clojars under my account and included that as the new dependency (mschristiansen/moustache "1.1.0") and 'lein deps' works as usual.

Might be from a new version of either lein or maven. I did a system upgrade yesterday.

**Comment by choffstein** [comment]
Ditto on this issue.

**Comment by scusack** [comment]
Yep same problem, here.
