### ISSUE TITLE
Bug in method dispatch

### ISSUE THREAD

**Issue by mtopolnik** [cgrand/moustache#8]
This one:

``` clojure
(app {:get [["foo"] (app {:keys [bar]} (fn [_] bar))]})
```

and this one:

``` clojure
(app {:get [["foo"] [{:keys [bar]} (fn [_] bar)]]})
```

should be exactly equivalent, but the former works and the latter fails with "Unable to resolve symbol: bar in this context".

**Comment by cgrand** [comment]
I'm afraid it's not a bug it's a feature. A map in last position of an app si considered to be a literal response map.
Thus {:get [["foo"](app {:keys [bar]} %28fn [_] bar%29)]} and {:get [["foo"] [{:keys [bar]} (fn [_] bar)]]} are treated as regular clojure code.
Unwrap your key/values and it will work in both cases.

The current syntaxic shorthands can be confusing. I haven't pushed the relevant commits but I have a new more regular syntax in the works.

**Comment by mtopolnik** [comment]
Thanks for the quick response. It is fascinating how Moustache is much easier to read than write; in most other languages/DSLs it's the other way around :)

**Comment by cgrand** [comment]
I'm writing the syntax file for the "modern" syntax, it should be better
albeit a little more verbose. The new syntax is not for change sake, it's
ground work for new semantics.

On Tue, Feb 5, 2013 at 11:53 AM, mtopolnik notifications@github.com wrote:

> Thanks for the quick response. It is fascinating how Moustache is much
> easier to read than write; in most other languages/DSLs it's the other way
> around :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cgrand/moustache/issues/8#issuecomment-13124032.

## 

On Clojure http://clj-me.cgrand.net/
Clojure Programming http://clojurebook.com
Training, Consulting & Contracting http://lambdanext.eu/

**Comment by mtopolnik** [comment]
I'll be sure to keep track on that progress because I love the spirit of Moustache. Meanwhile, I immediately ran into another, similar issue. This works:

``` clojure
(app :get [["foo" bar] (fn [_] bar)])
```

yet this doesn't:

``` clojure
(app :any [["foo" bar] (fn [_] bar)])
```

It fails with the same error as above: "Unable to resolve symbol: bar in this context". In fact, _anything_ else except `:any` works, even for example `:an`. It will just match a non-standard method AN.

**Comment by cgrand** [comment]
Can you open a new issue for this one? Thanks.

On Tue, Feb 5, 2013 at 12:28 PM, mtopolnik notifications@github.com wrote:

> I'll be sure to keep track on that progress because I love the spirit of
> Moustache. Meanwhile, I immediately ran into another, similar issue. This
> works:
> 
> (app :get [["foo" bar](fn [_] bar)])
> 
> yet this doesn't:
> 
> (app :any [["foo" bar](fn [_] bar)])
> 
> It fails with the same error as above: "Unable to resolve symbol: bar in
> this context". In fact, _anything_ else except :any works, even for
> example :an. It will just match a non-standard method AN.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cgrand/moustache/issues/8#issuecomment-13125141.

## 

On Clojure http://clj-me.cgrand.net/
Clojure Programming http://clojurebook.com
Training, Consulting & Contracting http://lambdanext.eu/

**Comment by cgrand** [comment]
The new syntax (and impl) are up http://cgrand.github.com/moustache/syntax.html

**Comment by mtopolnik** [comment]
Looks great: we can use the old syntax where it's working well, and seamlessly switch over to the explicit mode in a more complex part of the `app` form.

**Comment by mtopolnik** [comment]
I saw that your intent was to deprecate the legacy syntax so I switched the whole project over to the modern syntax. It went quite smooth and some parts of code are even less verbose due to the `:params [keys]` form. The only (very slight) annoyance is with the length of the :response keyword, which is heavily used throughout the `app` form.

**Comment by cgrand** [comment]
Thanks for the feedback. I considered :reply instead of (or as an alias) to
:response. Is it better to your eyes?

On Tue, Feb 5, 2013 at 6:58 PM, mtopolnik notifications@github.com wrote:

> I saw that your intent was to deprecate the legacy syntax so I switched
> the whole project over to the modern syntax. It went quite smooth and some
> parts of code are even less verbose due to the :params [keys] form. The
> only (very slight) annoyance is with the length of the :response keyword,
> which is heavily used throughout the app form.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cgrand/moustache/issues/8#issuecomment-13142629.

## 

On Clojure http://clj-me.cgrand.net/
Clojure Programming http://clojurebook.com
Training, Consulting & Contracting http://lambdanext.eu/

**Comment by mtopolnik** [comment]
It's shorter and is an OK word. On the semantic level :response is better, but maybe (if it's OK with your taste) :reply is a good compromise regarding character count. I also considered :resp, but I don't think you'd like it because everything else is full words.

**Comment by mtopolnik** [comment]
On the other hand, `:params` is a shortcut as well, albeit not introduced by Moustache. Maybe `:resp` is a viable consideration after all.
